import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          {/* Left Hero Section */}
          <div className={styles.leftherosection}>
            <div className={styles.image}>
              <Image src="/hero.jpg" alt="Coding" width={1000} height={600} />
              <div className={styles.content}>
                <h5>Software</h5>
                <h2>Running macOS and Windows 10</h2>
                <h2>on the Same Computer</h2>
                <p>
                  Cursus iaculis etiam in In nullam donec sem sed consequat
                  scelerisque nibh amet, massa egestas risus, gravida vel amet,
                  imperdiet ...
                </p>
              </div>
            </div>
          </div>

  <div className={styles.rightherosection}>
        <div className={styles.img}>

        </div>

        <div className={styles.rightcontent}>
          <h4>How to Learn Javascript in 2025?</h4>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil laudantium, labore aliquid esse corporis debitis dolorum repellendus maxime molestiae,.....</p>
         
           <button className={styles.button}><Link href="/blogs">Read More....</Link></button>
       
        </div>

        <div className={styles.rightcontent}>
          <h4>How to Learn Javascript in 2025?</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem necessitatibus eius quae cumque nisi omnis blanditiis dolor, exercitationem commodi! Labore?.....</p>
          <button className={styles.button}><Link href="/blogs">Read More....</Link></button>
        </div>

        <div className={styles.rightcontent}>
          <h4>How to Learn Javascript in 2025?</h4>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi nulla fugiat dolorem qui harum, quas culpa dolores corrupti sapiente molestiae?.....</p>
          <button className={styles.button}><Link href="/blogs">Read More....</Link></button>
        </div>
      </div>
          
        </main>
      </div>
    </>
  );
}

